<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AsyncRat.Panel</RootNamespace>
    <AssemblyName>asyncrat</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\async-rat.Client\async-rat.Client.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
